const UsersData = {
  Kit: {
    tabName: "Kit",
    data: {
      tableHeading: [
        "CustomerName",
        "Card No.",
        "Email Id",
        "Mobile No.",
        "Card Network",
        "Activation",
        "Action",
      ],
      users: [
        {
          accId: "605435a-72sd-bhsd7-sjsd6-927g5hajb2",
          kitNumber: null,
          name: "Himanshu",
          program: null,
          customerId: null,
          number: "-",
          email: "himsag@gmail.com",
          mobile: "8197999024",
          cardNetwork: "-",
          expiry: "21/09/2022",
          activation: null,
          status: null,
          isVerified: false,
        },
        {
          accId: "sjdk7-72sd-bhsd7-sjsd6-jhdjfy6bsj",
          kitNumber: null,
          name: "corp4_customer",
          program: null,
          customerId: null,
          number: "5520 00144",
          email: "nfsInfl@Idnglsfdsf.sddgs",
          mobile: "9022197577",
          cardNetwork: "RuPay",
          expiry: "21/09/2022",
          activation: null,
          status: null,
          isVerified: true,
        },
      ],
    },
  },
  "Personalised Sale": {
    tabName: "Personalised Sale",
    data: {
      tableHeading: [
        "Name",
        "Program Name",
        "Customer Id",
        "Card No",
        "ExpiryDate",
        "Activation",
        "Status",
        "Details",
      ],
      users: [
        {
          accId: "sjd68av-72sd-hsds-sjsd6-267bsbd",
          kitNumber: null,
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "ABCD1234",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Approved",
          isVerified: null,
        },
        {
          accId: "898s889vabs-sd-23ss-xhgs-uwy6vw",
          kitNumber: null,
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "-",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Rejected",
          isVerified: null,
        },
        {
          accId: "skjds7772vs-sd-23ss-xhgs-aj8",
          kitNumber: null,
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "-",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Pending",
          isVerified: null,
        },
      ],
    },
  },
  Reissue: {
    tabName: "Reissue",
    data: {
      tableHeading: [
        "Kit No",
        "Name",
        "Program Name",
        "Customer ID",
        "Card No",
        "Expiry",
        "Activation",
        "Status",
        "Details",
      ],
      users: [
        {
          accId: "ajhs-sd-asa-87abnbnsas-87hjasb2",
          kitNumber: "GDYG372873123",
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "-",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Approved",
          isVerified: null,
        },
        {
          accId: "jhjas2-2xzd-23jkajks-xhgs-uwy6vw",
          kitNumber: "GDYG372873123",
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "-",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Rejected",
          isVerified: null,
        },
        {
          accId: "87wgaaa-sd-23ss-xhgs-kjks5vqvqj",
          kitNumber: "GDYG372873123",
          name: "Ronit Bhandari",
          program: "Ebix Cash 1",
          customerId: "-",
          number: "-",
          email: null,
          mobile: null,
          cardNetwork: null,
          expiry: "21/09/2022",
          activation: "21/09/2022",
          status: "Pending",
          isVerified: null,
        },
      ],
    },
  },
};

export { UsersData };
